---
  - name: install_wireguardVPN
    hosts: Linux3
    
    vars:
      source_file: ~/knowledge_progress/Ansible/playbooks/docker-compose.yml
      destination_file: /root
    
    tasks:
      
      - name: install docker
        apt:
          update_cache: yes
          name: docker
          state: latest
      
      - name: install docker.io
        apt:
          name: docker.io
          state: latest

      - name: Install docker-compose
        get_url: 
          url : https://github.com/docker/compose/releases/download/v2.14.2/docker-compose-Linux-x86_64
          dest: /usr/local/bin/docker-compose
          mode: 'u+x,g+x'


      - name: Download docker-compose.yml config 
        get_url: 
          url : https://github.com/aquecola/docker_wireguard/releases/download/docker/docker-compose.yml
          dest: /root

      
      - name: Run container
        become: True
        shell:
          cmd: "docker-compose up -d"
          chdir: /root/